pipeline {
    agent any

    parameters {
        string(name: 'BRANCH_NAME', defaultValue: '', description: 'Enter branch name')
    }

    environment {
        RESOURCE_GROUP = "CloudFrame-RG"
    }


    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Download Artifact From CI') {
            steps {
                copyArtifacts(
                    projectName: 'DemoPipeline10',  // 🔥 replace
                    selector: lastSuccessful(),
                    fingerprintArtifacts: true
                )
            }
        }

        stage('Azure Login') {
            steps {
                withCredentials([
                    string(credentialsId: 'AZ_CLIENT_ID', variable: 'CID'),
                    string(credentialsId: 'AZ_CLIENT_SECRET', variable: 'CSEC'),
                    string(credentialsId: 'AZ_TENANT_ID', variable: 'TID'),
                    string(credentialsId: 'AZ_SUB_ID', variable: 'SID')
                ]) {
                    bat '''
                    az login --service-principal -u %CID% -p %CSEC% --tenant %TID%
                    az account set --subscription %SID%
                    '''
                }
            }
        }

        stage('Deploy Storage Account - DEV ENV') {
            steps {
                bat '''
                az deployment group create ^
                --name dev-storage-%BUILD_NUMBER% ^
                --resource-group %RESOURCE_GROUP% ^
                --template-file azure-adf-e2e\\arm-templates\\storage-account\\storage.json ^
                --parameters storageAccounts_cftproject_name=cfstorage001prod%BUILD_NUMBER% ^
                --mode Incremental ^
                --output none

                IF %ERRORLEVEL% NEQ 0 (
                    echo Deployment failed!
                    exit /b 1
                )

                echo Deployment completed successfully.
                '''
            }
        }
    }
}